"""Export final APD-SIM-3/6/9 single-image source data.

The default Cell_054 identity is taken from the completed formal 30-FOV run,
so this exporter cannot silently fall back to an older checkpoint or regenerate
a best-of-N trajectory.  All three stored raw bundles were independently
generated by ``evaluate_apd369_protocols_final.py``.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
from pathlib import Path
import sys
from typing import Any, Mapping, Sequence

import numpy as np
import tifffile


ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from tools.apd369_final_contract import DEFAULT_OUTPUT_ROOT, PLANS, atomic_json, read_json, sha256_file  # noqa: E402
from tools import revision_dmd6_common as common  # noqa: E402
from unisim.revision_r1 import frame_budget_r1c2 as fb  # noqa: E402


DEFAULT_GT = Path(r"data/sealed_test_gt\microtubules_Cell_054_SIM_gt.tif")
PRESELECTED_STRUCTURE_ORDERS = {"CCP": 0, "ER": 10, "MT": 20}


def _write_csv(path: Path, rows: Sequence[Mapping[str, Any]], fields: Sequence[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(fields), lineterminator="\n")
        writer.writeheader(); writer.writerows(rows)


def _save_float_pair(directory: Path, name: str, value: np.ndarray) -> None:
    directory.mkdir(parents=True, exist_ok=True)
    array = np.ascontiguousarray(value, dtype=np.float32)
    np.save(directory / f"{name}.npy", array, allow_pickle=False)
    tifffile.imwrite(directory / f"{name}.tif", array)


def _spectrum(value: np.ndarray) -> np.ndarray:
    centered = np.asarray(value, dtype=np.float64) - float(np.mean(value))
    spectrum = np.log1p(np.abs(np.fft.fftshift(np.fft.fft2(centered))))
    low, high = float(spectrum.min()), float(spectrum.max())
    if not math.isfinite(low) or not math.isfinite(high) or high <= low:
        raise ValueError("invalid spectrum")
    return np.ascontiguousarray((spectrum - low) / (high - low), dtype=np.float32)


def _find_sample(manifest: Mapping[str, Any], gt_path: Path) -> Mapping[str, Any]:
    digest = sha256_file(gt_path)
    matches = [row for row in manifest["samples"] if row["file_sha256"] == digest]
    if len(matches) != 1:
        raise RuntimeError("input GT is not a unique identity in the frozen 30-FOV manifest")
    return matches[0]


def _export_one(
    output_root: Path,
    sample: Mapping[str, Any],
    target: Path,
    metric_rows: Sequence[Mapping[str, str]],
    *,
    full_assets: bool,
) -> dict[str, Any]:
    order = int(sample["order"])
    gt = fb.normalize_image(tifffile.imread(Path(sample["absolute_path"])))
    arrays: dict[str, np.ndarray] = {"GT": gt}
    raw_receipts = []
    for plan in PLANS:
        native_source = output_root / "03_harmonized_outputs" / "native" / plan.method / f"{order:03d}_{sample['sample_id']}.npy"
        harmonized_source = output_root / "03_harmonized_outputs" / "harmonized" / plan.method / f"{order:03d}_{sample['sample_id']}.npy"
        raw_source = output_root / "02_protocol_raw_bundles" / plan.method / f"{order:03d}_{sample['sample_id']}.npz"
        if not native_source.is_file() or not harmonized_source.is_file() or not raw_source.is_file():
            raise RuntimeError(f"formal output missing for {plan.method}/{sample['sample_id']}")
        native = np.load(native_source, allow_pickle=False)
        harmonized = np.load(harmonized_source, allow_pickle=False)
        if not np.isfinite(native).all() or not np.isfinite(harmonized).all():
            raise RuntimeError("non-finite formal output")
        arrays[plan.method] = np.ascontiguousarray(harmonized, dtype=np.float32)
        _save_float_pair(target / "native", plan.method, native)
        _save_float_pair(target / "harmonized", plan.method, harmonized)
        bundle = np.load(raw_source, allow_pickle=False)
        raw = np.ascontiguousarray(bundle["raw_stack"], dtype=np.float32)
        raw_dir = target / "native" / f"raw_{plan.method}"
        raw_dir.mkdir(parents=True, exist_ok=True)
        np.save(raw_dir / "raw_stack.npy", raw, allow_pickle=False)
        for index, label in enumerate(plan.raw_order):
            tifffile.imwrite(raw_dir / f"{index:02d}_{label}.tif", raw[index])
        raw_receipts.append({
            "method": plan.method, "protocol_id": plan.protocol_id,
            "raw_frame_order": list(plan.raw_order), "raw_stack_sha256": common.array_sha256(raw),
            "source_npz": str(raw_source.resolve()), "source_npz_sha256": sha256_file(raw_source),
            "generation_call_uuid": str(bundle["generation_call_uuid"].item()),
        })
    _save_float_pair(target / "native", "GT", gt)
    _save_float_pair(target / "harmonized", "GT", gt)
    for name, value in arrays.items():
        _save_float_pair(target / "spectra", name, _spectrum(value))
        (target / "display16").mkdir(parents=True, exist_ok=True)
        tifffile.imwrite(target / "display16" / f"{name}.tif", np.rint(np.clip(value, 0, 1) * 65535).astype(np.uint16))
    profile_rows = []
    y = gt.shape[0] // 2
    for x in range(gt.shape[1]):
        row = {"sample_id": sample["sample_id"], "profile_id": "horizontal_center", "x": x, "y": y}
        row.update({name: float(value[y, x]) for name, value in arrays.items()})
        profile_rows.append(row)
    _write_csv(target / "profiles" / "profile_source_data.csv", profile_rows, tuple(profile_rows[0]))
    frc_rows = []
    for name, value in arrays.items():
        meta, curve = common.gt_frc(gt, value)
        for frequency, frc_value, count in zip(
            curve["frequency_cycles_per_pixel"], curve["frc"], curve["count"], strict=True
        ):
            frc_rows.append({
                "sample_id": sample["sample_id"], "method": name,
                "frequency_cycles_per_pixel": float(frequency),
                "frc": float(frc_value), "annulus_pixel_count": int(count),
                "threshold": meta["threshold"],
            })
    _write_csv(target / "frc" / "FRC_curves.csv", frc_rows, tuple(frc_rows[0]))
    selected_metrics = [row for row in metric_rows if int(row["order"]) == order]
    _write_csv(target / "single_image_metrics.csv", selected_metrics, tuple(selected_metrics[0]))
    checkpoint_receipts = [
        {
            "method": row["method"],
            "protocol_id": row["protocol_id"],
            "protocol_hash": row["protocol_hash"],
            "checkpoint_path": row["checkpoint_path"],
            "checkpoint_sha256": row["checkpoint_sha256"],
            "inference_weight_branch": row["inference_weight_branch"],
            "diffusion_seed": int(row["diffusion_seed"]),
        }
        for row in selected_metrics
    ]
    receipt = {
        "sample": dict(sample), "full_assets": bool(full_assets),
        "source_formal_evaluation_root": str(output_root.resolve()),
        "independently_generated_raw_bundles": True,
        "common_nine_frame_subsampling_count": 0,
        "checkpoint_protocol_receipts": checkpoint_receipts,
        "raw_receipts": raw_receipts,
    }
    atomic_json(target / "figure_source_receipt.json", receipt)
    return receipt


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--gt", type=Path, default=DEFAULT_GT)
    parser.add_argument("--output-root", type=Path, default=DEFAULT_OUTPUT_ROOT)
    parser.add_argument("--target", type=Path, default=None)
    args = parser.parse_args()
    output_root = args.output_root.resolve()
    manifest = read_json(output_root / "01_test_manifest" / "test30_manifest.json")
    metrics_path = output_root / "04_metrics" / "per_fov_metrics.csv"
    if not metrics_path.is_file():
        raise RuntimeError("formal 30-FOV evaluation is not complete")
    with metrics_path.open("r", encoding="utf-8-sig", newline="") as handle:
        metric_rows = list(csv.DictReader(handle))
    if len(metric_rows) != 90:
        raise RuntimeError("formal 90-row protocol grid is incomplete")
    sample = _find_sample(manifest, args.gt.resolve())
    target = args.target.resolve() if args.target is not None else output_root / "05_figure3_source"
    primary = _export_one(output_root, sample, target, metric_rows, full_assets=True)
    selections = []
    for structure, order in PRESELECTED_STRUCTURE_ORDERS.items():
        candidate = next(row for row in manifest["samples"] if int(row["order"]) == order)
        if candidate["class"] != structure:
            raise RuntimeError("preselected structure order drift")
        subdir = target / "supplementary_structures" / structure
        _export_one(output_root, candidate, subdir, metric_rows, full_assets=False)
        selections.append({"structure": structure, "order": order, "sample_id": candidate["sample_id"], "selection_basis": "pre-registered order before output inspection"})
    atomic_json(target / "preselected_structure_sources.json", {"selections": selections})
    print(json.dumps({"status": "APD369_FIGURE_SOURCE_READY", "target": str(target), "primary": primary["sample"]["sample_id"]}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
